theme: minima
markdown: kramdown

title: |-
    Calibration of an Elastic Humanoid Upper Body
    and Efficient Compensation for Motion Planning

author: johannes.tenhumberg@dlr.de

header_pages:
  - _pages/robot.md
  - _pages/methods.md
  - _pages/results.md
  - _pages/dataset.md

include:
    - _pages
    
exclude: 
    - .gitignore
    - Gemfile
    - README.md
